### ISSUE TITLE
Segmentation Fault (Core Dumped)

### ISSUE THREAD

**Issue by ashiqimran** [salaniz/pytorch-gve-lrcn#11]
I am getting error ''Segmentation fault (core dumped)". Any suggestions?

**Comment by salaniz** [comment]
Hard to say without any more information. Can you please provide the full error log?
Most importantly, I need to know where exactly this happens.

**Comment by ashiqimran** [comment]
After I installed all the required packages, I want to start training on MS-coco datasets.  After I pass the following command, I am getting the error message. 
python main.py --model lrcn --dataset coco

**Comment by salaniz** [comment]
Unfortunately this is not enough information to work with.
I have updated the installation with a conda environment that should make it easier to run this repository. Please make a fresh start and check if it is working now.
You can reopen this issue if your problems have not been resolved, but please give the full error message or debug the code to more closely tell me where the segmentation fault exactly happens.
