### ISSUE TITLE
CUB data access

### ISSUE THREAD

**Issue by AngB0l** [salaniz/pytorch-gve-lrcn#14]
Hello and thank you for your work!
I am trying to reproduce the results from GVE but the URL:
https://people.eecs.berkeley.edu/~lisa_anne/generating_visual_explanations/data/ is now password protected.
Is there any other way to access the data files of CUB?
Thank you in advance

**Comment by Elendor11** [comment]
I had a similar issue, this might be too late of an answer. On the Lisa Anna's own implementation she explains she had to move the dataset to Google Drive. The link should be this https://drive.google.com/drive/folders/1nU9ATTLHAM6_jz-K6hoVlDzNrFcOXtyH
I hope this helps you or others!

**Comment by salaniz** [comment]
The `cub-data-setup-linux.sh` script now uses the google drive resources to download and setup the data.
