### ISSUE TITLE
Lengths of data too long while training GVE

### ISSUE THREAD

**Issue by Elendor11** [salaniz/pytorch-gve-lrcn#15]
There is an issue I had while training GVE, the length that LRCN outputs gets way too big for the data, resulting eventually in memory issues when trying to use the Sentence Classifier.
I've found that line 133 of the LRCN class: "active_batches = (~reached_end)" does not switch the zeros to ones, but rather switches them to 255 in this version of Pytorch.
A simple fix I've found for this is to use (reached_end^1), this solved the problem for me!
I hope this can help others with a similar issue!

**Comment by Ellyuca** [comment]
hi @Elendor11.
Did you manage to train the gve? if so, could you share your pretrained model?

Thanks.

**Comment by katelyn98** [comment]
This solution (reached_end^1) also fixed the training for me. Thank you!

**Comment by salaniz** [comment]
The behavior of pytorch changed some time ago, so I fixed the code to use a boolean tensor now.
