### ISSUE TITLE
Grounding Visual Explanations

### ISSUE THREAD

**Issue by muneeb699** [salaniz/pytorch-gve-lrcn#8]
Hi Salaniz,

There is an extension to this paper you implemented in pytorch:
Grounding Visual Explanations ( https://arxiv.org/abs/1807.09685 ). I am intrested in that. Do you have any plan to implement that.

p.s: sorry for contacting like this 

Regrads

**Comment by salaniz** [comment]
Hi, I currently have no plans on implementing the extensions introduced in "Grounding Visual Explanations".
